# AquaExport Pro 2.0 Configuration File
# Edit these settings to match your environment

[database]
# PostgreSQL connection settings
host = "localhost"
port = 5432
name = "SCADA_arhiva_rab"
user = "postgres"
password = "fornax123"

[export]
# Export settings
directory = "./exports"           # Where to save Excel files
template_path = "./template.xlsx" # Path to Excel template

# Tag mappings based on PLC addresses from electrical engineers
# PK Barbat: N12:7 (turbidity), N12:8 (chlorine), N12:9 (pH), N12:10 (temp), N12:11 (redox)
# VS Lopar: N22:3 (chlorine), N22:7 (temp), N22:9 (redox)
# VS Perici: N15:40 (chlorine), N15:41 (redox), N15:42 (temp)

[tag_mappings.pk_barbat]
mutnoca = 3    # N12:7 - Turbidity (NTU)
klor = 21      # N12:8 - Chlorine (mg/l) - Note: This is trend_klora_izlaza, might need verification
temp = 134     # N12:10 - Temperature (°C)
pH = 132       # N12:9 - pH value
redox = 133    # N12:11 - Redox potential (mV)

[tag_mappings.vs_lopar]
# VS Lopar only measures 3 parameters (no turbidity or pH)
klor = 151     # N22:3 - Chlorine (mg/l)
temp = 155     # N22:7 - Temperature (°C)
redox = 156    # N22:9 - Redox potential (mV)

[tag_mappings.vs_perici]
# VS Perici only measures 3 parameters (no turbidity or pH)
klor = 72      # N15:40 - Chlorine (mg/l)
temp = 82      # N15:42 - Temperature (°C)
redox = 81     # N15:41 - Redox potential (mV)